// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jb2IOOpyrkZCDjlNLiG1HZA8RJBDAFI',
    appId: '1:341391992032:web:7f0c8e5498ecda69401c85',
    messagingSenderId: '341391992032',
    projectId: 'flutix-30e41',
    authDomain: 'flutix-30e41.firebaseapp.com',
    storageBucket: 'flutix-30e41.appspot.com',
    measurementId: 'G-K6JD3QSJ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY66jHQ1K9Qo4lfcN6TSc05EC89PlZnbE',
    appId: '1:341391992032:android:be18be6e71f8a59b401c85',
    messagingSenderId: '341391992032',
    projectId: 'flutix-30e41',
    storageBucket: 'flutix-30e41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyL_BRLNU4xmV5dLzC-xPt4NEirImX0Y',
    appId: '1:341391992032:ios:93d0274b602f2fb6401c85',
    messagingSenderId: '341391992032',
    projectId: 'flutix-30e41',
    storageBucket: 'flutix-30e41.appspot.com',
    iosClientId:
        '341391992032-tmd0a81f2tutjnmat1nucutot4nhd5qr.apps.googleusercontent.com',
    iosBundleId: 'com.fathdotdev.flutix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyL_BRLNU4xmV5dLzC-xPt4NEirImX0Y',
    appId: '1:341391992032:ios:93d0274b602f2fb6401c85',
    messagingSenderId: '341391992032',
    projectId: 'flutix-30e41',
    storageBucket: 'flutix-30e41.appspot.com',
    iosClientId:
        '341391992032-tmd0a81f2tutjnmat1nucutot4nhd5qr.apps.googleusercontent.com',
    iosBundleId: 'com.fathdotdev.flutix',
  );
}
